### ISSUE TITLE
Add VictoriaMetrics as storage backend and PromQL executor

### ISSUE THREAD

**Issue by valyala** [cloudfoundry/metric-store-release#37]
### Is this an Issue/Bug or a Feature Request?

[ ] Issue or Bug
[x] Feature Request

### Why do you want this feature?

`metric-store` [uses InfluxDB](https://github.com/cloudfoundry/metric-store-release/blob/680d720b802433ffcb5bb3db33cc1bdb9cff6c2c/src/pkg/persistence/influx_store.go#L6) as storage backend. It would be great to add ability to use [VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics/) as storage backend, since it requires less CPU, RAM and storage space comparing to InfluxDB. See the following articles for details:
* https://medium.com/@valyala/insert-benchmarks-with-inch-influxdb-vs-victoriametrics-e31a41ae2893
* https://medium.com/@valyala/measuring-vertical-scalability-for-time-series-databases-in-google-cloud-92550d78d8ae
* https://medium.com/@valyala/when-size-matters-benchmarking-victoriametrics-vs-timescale-and-influxdb-6035811952d4
* https://medium.com/faun/victoriametrics-achieving-better-compression-for-time-series-data-than-gorilla-317bc1f95932

Additionally, VictoriaMetrics provides high-performance PromQL engine written from scratch. The engine provides [extended functionality](https://github.com/VictoriaMetrics/VictoriaMetrics/wiki/ExtendedPromQL) on top of standard PromQL. It would be great if PromQL engine from VictoriaMetrics could be added into `metric-store` as an alternative to existing PromQL engine.

**Comment by heidmotron** [comment]
Hi @valyala! Thanks for submitting this feature request. At this time we're not looking to extend the architecture for pluggable storage engines.
